# Generated by Django 3.2.11 on 2022-01-08 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='Blog/images')),
                ('url', models.CharField(max_length=50)),
                ('date', models.DateField(verbose_name=datetime.date.today)),
            ],
        ),
    ]
